apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: n8n

  source:
    repoURL: https://8gears.container-registry.com/chartrepo/library
    chart: n8n
    targetRevision: 0.18.0
    helm:
      valueFiles:
        - $values/k8s/infra/n8n/values.yaml

  sources:
    - repoURL: https://8gears.container-registry.com/chartrepo/library
      chart: n8n
      targetRevision: 0.18.0
    - repoURL: https://github.com/cezarymostowiec/homelab-proxmox.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
