main:
  config:
    n8n:
      basicAuth:
        active: true
        user: admin
      host: n8n.lab.local
      port: 443
      protocol: https
      webhook:
        url: https://n8n.lab.local
  extraEnv:
    - name: N8N_BASIC_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: n8n-credentials
          key: N8N_BASIC_AUTH_PASSWORD
    - name: N8N_TRUST_PROXY
      value: "true"
  persistence:
    enabled: true
    type: dynamic
    storageClass: local-path
    size: 5Gi

service:
  type: ClusterIP

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
  hosts:
    - host: n8n.lab.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - n8n.lab.local
      secretName: n8n-tls
