configs:
  params:
    server.insecure: true

server:
  replicas: 1

  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.lab.local

    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

    tls: true

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1

redis:
  enabled: true

dex:
  enabled: false

notifications:
  enabled: false
