---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgByj1VId+wBE3dJcLe4TjZUj/jTSq+KqCWnFzE15nK8xvWbvZmtUb1Uwk094pUezvcbNZPc1zT1xaTZmQYUr0DARq8PIUh84oQ4I2l93+g0CB1R0yNI4zoStyhGGxpsG94sg1RtzoBtnsy27o5J0RtFZ/giWlZeX2yYwczI/mVHzKc4+BhvA9NNJuLUyj+Aqsf9DYLZTRVBcrimTyT4zqjeehc4lvSdzNmUj7bUs4glHZbpxIIGz23GlqIeTYMd5fpdYEUc0BYF951YYhkQiOuhvD8AMSbb2wNU0SnWLMZk/Id2iGZuCO/AiAiQFCdbp1RAnnPnZ3X7WOD9brEKW/7wbGL+UVh+qtFAsGSKfghXAJLape8aOWVztrmcMWIbgRd9XR0d/lmQ531NagWgVWqu26heKXScvhmKYG55Ja5ISgV7T9PtQNlvOB4Oyq2BYZqesCoPro6/tVn0J8+k68w7lD2c1TouUeUDvhK3FE8Eoq1v74+0Q+nSFug0E+OHCpqq1rLBrZTXf8CLONqa89BMWestwKa8ZqZzTEjwitsP3rULuULECU477Tgh0pZiPaH18A5i+ekg2Msd+/xby8mj3TwuZuDUNenP49l2OVy50w7GZo4SCP+NIiz104S3I1ADST+VFkzcTk5p3uqA94bxtWdnNKlL7KQ5yUlJ2OidkU3pBJGAM40lLqc0QRxpTcWFs1jxblMv75ACfznbNmL89SYMfrYPDTpLgFYOZNL0dcRaxsjzKSausgKh6ozTG0VMEs2M8bFjPGMG+zoCwgaT7QAfIz9p1Ho+W1D43di3sKAKhOLas4Aegg7lWeEMRtpqzgmx3DWGaSf461QCrxQ=
  template:
    metadata:
      name: velero-credentials
      namespace: velero
