credentials:
  existingSecret: velero-credentials

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero-backups
      credential:
        name: velero-credentials
        key: cloud
      config:
        region: minio
        s3ForcePathStyle: "true"
        s3Url: http://minio.minio.svc.cluster.local:9000

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.11.0
    volumeMounts:
      - mountPath: /target
        name: plugins

schedules:
  daily-backup:
    disabled: false
    schedule: "0 2 * * *"
    useOwnerReferencesInBackup: false
    template:
      ttl: 720h
      includedNamespaces:
        - argocd
        - monitoring
        - n8n
        - minio
        - loki
        - alloy
