---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-credentials
  namespace: n8n
spec:
  encryptedData:
    N8N_BASIC_AUTH_PASSWORD: AgA+XEx+hObnWFdq2SILgOT8gsGG1vKp5s0wIoQay2iO2a122d4FfNZO/0pvPSwNKSZdb37204UM8vF/DfBmGhuHa02Sg7gnF0DcOicq936ApIvdzHQgn1LCMcTHeJVTVjHjusJdwXwlNSY3vrYksl0EMWG79Qlc+KVyhfkcIHspCMX8+y2EPkx9cevi5AIShCywKuHuLSa4LJS48uqvUCvxcrUOrD74qj9VcoE6F6tsYgjOUUtGl20QfcqTrQTQYKXCP4XCbZ0l8I5Qz8ee1fLXTJ6+ciKfiu9xsC5BS+F08AWrr5DJwUL+qtw/wrnj5zK3on7CN9RKIg9DuOtw3ijPuSViI3/MqsEK35Sclly6QOjUAPp8knfpzxOKkIe052iNvj3aBAjD3z9WuDJ6CUIqB7wg84Hwe1cjpnduFzwF+DC4nrPvc5YFZBXrKzjZS0ieKfTNIMH7/yAge/VO+gnx7fd0N5y38tgBGQpJSqcIBYRqqjYngpgRhH2+81b0FqmKxRUh/K0fewMBgG9WJSsk+gAdq8Aylm5E77YKktMUlh6MiwUSNXB9DNA12+WgxuUDw2DnG8F2dmMRj7pkGSOjB1G2StkTR7F3hejnCUox1lo3p/6FjC8NmGEYhZWSLZUs9BpwppbCgHC7gucnmYdzEXLINn0BQfgQGmihOKLQ8Bg3SlMohJpo1KJQt8ko4PxCpJ16QBOCfA==
  template:
    metadata:
      name: n8n-credentials
      namespace: n8n
